CREATE TABLE IF NOT EXISTS "surviving-maps-3d_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "surviving-maps-3d_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_breakthrough" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "surviving-maps-3d_breakthrough_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_en" varchar(256),
	"name_br" varchar(256),
	"name_fr" varchar(256),
	"name_ge" varchar(256),
	"name_po" varchar(256),
	"name_ru" varchar(256),
	"name_sc" varchar(256),
	"name_sp" varchar(256),
	"desc_en" text,
	"desc_br" text,
	"desc_fr" text,
	"desc_ge" text,
	"desc_po" text,
	"desc_ru" text,
	"desc_sc" text,
	"desc_sp" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_breakthrough_in_location" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "surviving-maps-3d_breakthrough_in_location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bt_id" integer NOT NULL,
	"loc_id" integer NOT NULL,
	"ver_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_location" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "surviving-maps-3d_location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lat_dir" varchar(1),
	"lat_deg" varchar(3),
	"lon_dir" varchar(1),
	"lon_deg" varchar(3),
	"altitude" integer,
	"named_loc_id" integer,
	"map_name" varchar(256),
	"topography" varchar(256),
	"concrete" integer,
	"water" integer,
	"metals" integer,
	"rare_metals" integer,
	"temperature" integer,
	"meteors" integer,
	"dust_devils" integer,
	"dust_storms" integer,
	"cold_waves" integer,
	"difficulty" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_named_location" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "surviving-maps-3d_named_location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name_en" varchar(256),
	"name_br" varchar(256),
	"name_fr" varchar(256),
	"name_ge" varchar(256),
	"name_po" varchar(256),
	"name_ru" varchar(256),
	"name_sc" varchar(256),
	"name_sp" varchar(256)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "surviving-maps-3d_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "surviving-maps-3d_version" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "surviving-maps-3d_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256)
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "surviving-maps-3d_account" ADD CONSTRAINT "surviving-maps-3d_account_user_id_surviving-maps-3d_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."surviving-maps-3d_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "surviving-maps-3d_session" ADD CONSTRAINT "surviving-maps-3d_session_user_id_surviving-maps-3d_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."surviving-maps-3d_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "surviving-maps-3d_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "surviving-maps-3d_session" USING btree ("user_id");